# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_add_related_name_UserInfo_user_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
