# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_add_upload_to_UserInfo_profile_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='dream',
            field=models.TextField(blank=True),
        ),
    ]
