# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ranking',
            field=models.IntegerField(null=True),
        ),
    ]
